### ISSUE TITLE
The game crashes after some time of playing on the server

### ISSUE THREAD

**Issue by iNightboat** [kamyu1537/WebFishingDedicatedServer#2]
I don't know what it is, a bug or some other problem, but after about 3-5 minutes on a running server (as a host), the game crashes without any errors. The server itself does not close, and the console does not issue errors.

I checked on the latest version of the program, on a clean, unmodified client. I'm not sure that this is how it should happen, so I wrote about it here in order to understand the situation.

**Comment by iNightboat** [comment]
I want to add that if the server is turned on by itself, then nothing will happen to it.
This problem only affects the moment when you log on to the server as a host. You can stay on it for at most 5 minutes, after which the game closes.

**Comment by kamyu1537** [comment]
hmm.. i will check it.

**Comment by kamyu1537** [comment]
1. could you let me know the memory capacity of the PC running the server?
2. running the server alongside the game may cause errors to occur.

you need to purchase the webfishing on a different account and log in with the purchased account on another computer with Steam running for the server to operate properly.

**Comment by iNightboat** [comment]
RAM 32GB, do I understand correctly that you need to have 2 accounts with a copy of the game, one of which must have a server running so that the other can play on it?

**Comment by iNightboat** [comment]
I also checked version 1.1.12. Although I am alone on the server, it has clearly been more than 5 minutes, and the game still hasn't crashed. I'll try to check if there is a friend on the server. I will also indicate the result below

**Comment by iNightboat** [comment]
The problem arises when someone else is playing on the server besides you. Instant departure in the first minute after the player enters. If the only solution to this problem is to purchase the game on another account, then this is sad

**Comment by iNightboat** [comment]
Additional information: the console constantly displays errors related to another player on the server. They are displayed regardless of whether the other player is doing something or not. They just show up. 
And if I noticed correctly, this happens only after my game crashes.

https://github.com/user-attachments/assets/a24e22c7-c88a-407a-a2cf-0845d0cbfc04

specifically in this case, I flew out after the other player started to quickly press the G and K buttons (kiss and meow).

**Comment by kamyu1537** [comment]
1. Webfishing does not support dedicated servers in the same way as typical Steam games.
2. Webfishing supports multiplayer by using Steam's game lobby functionality.
3. All open source "dedicated server" projects currently available are not true dedicated servers; instead, they emulate a client.
4. Due to this limitation, you need two accounts that own the game, each logged in on a different PC to run the server.
5. If you open the server and connect to the game using the same account, even on a different computer, it may cause network communication issues and crash the game.
6. Even if you run the server with the same account and then separately launch the game to connect to another server, issues may still occur.
